CREATE TABLE IF NOT EXISTS sys_operation_log (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    user_id BIGINT NULL,
    username VARCHAR(64) NULL,
    biz_module VARCHAR(64) NOT NULL,
    operation_type VARCHAR(64) NOT NULL,
    request_method VARCHAR(16) NOT NULL,
    request_uri VARCHAR(255) NOT NULL,
    request_params VARCHAR(1000) NULL,
    success TINYINT NOT NULL DEFAULT 1,
    status_code INT NOT NULL,
    duration_ms BIGINT NOT NULL DEFAULT 0,
    remote_ip VARCHAR(64) NULL,
    error_message VARCHAR(1000) NULL,
    create_by VARCHAR(64) NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by VARCHAR(64) NULL,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_sys_operation_log_tenant_id (tenant_id),
    KEY idx_sys_operation_log_username (username),
    KEY idx_sys_operation_log_biz_module (biz_module),
    KEY idx_sys_operation_log_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='System operation log';
