CREATE TABLE IF NOT EXISTS sys_codegen_table (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    physical_table_name VARCHAR(128) NOT NULL,
    table_comment VARCHAR(255) NULL,
    business_name VARCHAR(64) NOT NULL,
    class_name VARCHAR(128) NOT NULL,
    module_name VARCHAR(64) NOT NULL,
    package_name VARCHAR(255) NOT NULL,
    gen_mode VARCHAR(32) NOT NULL DEFAULT 'crud',
    column_count INT NOT NULL DEFAULT 0,
    remark VARCHAR(255) NULL,
    create_by VARCHAR(64) NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by VARCHAR(64) NULL,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_sys_codegen_table_tenant_name (tenant_id, physical_table_name),
    KEY idx_sys_codegen_table_business_name (business_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Codegen table metadata';

CREATE TABLE IF NOT EXISTS sys_codegen_column (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    table_id BIGINT NOT NULL,
    column_name VARCHAR(128) NOT NULL,
    column_comment VARCHAR(255) NULL,
    jdbc_type VARCHAR(64) NOT NULL,
    java_type VARCHAR(64) NOT NULL,
    java_field VARCHAR(128) NOT NULL,
    html_type VARCHAR(32) NOT NULL DEFAULT 'input',
    query_type VARCHAR(32) NOT NULL DEFAULT 'LIKE',
    required TINYINT NOT NULL DEFAULT 0,
    list_visible TINYINT NOT NULL DEFAULT 1,
    form_visible TINYINT NOT NULL DEFAULT 1,
    status TINYINT NOT NULL DEFAULT 0,
    create_by VARCHAR(64) NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by VARCHAR(64) NULL,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_sys_codegen_column_tenant_table_column (tenant_id, table_id, column_name),
    KEY idx_sys_codegen_column_table_id (table_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Codegen column metadata';
