CREATE TABLE IF NOT EXISTS sys_department (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    parent_id BIGINT NOT NULL DEFAULT 0,
    department_name VARCHAR(100) NOT NULL,
    leader VARCHAR(100) NULL,
    phone VARCHAR(32) NULL,
    email VARCHAR(100) NULL,
    sort INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 0,
    remark VARCHAR(255) NULL,
    create_by VARCHAR(64) NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by VARCHAR(64) NULL,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_sys_department_tenant_parent_name (tenant_id, parent_id, department_name),
    KEY idx_sys_department_parent (parent_id),
    KEY idx_sys_department_status (status),
    KEY idx_sys_department_sort (sort)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='System department';
